Add test case for Logger call without blank?
Rollbar does not have ActiveSupport as
a runtime dependency in gemspec and it is
not required in Rollbar::Logger but is used.

way to reproduce:

```irb
require 'rollbar/logger'
Rollbar::Logger.new.error("foo")
  # NoMethodError: undefined method `blank?' for "foo":String
```

can be worked arround by requiring
`active_support/core_ext/object/blank`

```irb
require 'rollbar/logger'
require 'active_support/core_ext/object/blank'
Rollbar::Logger.new.error("foo")
  # => "disabled"
```